const items = [
  'Ex consequat nulla exercitation occaecat velit quis aliqua quis do.',
  'Et incididunt magna ipsum culpa deserunt.',
  'Enim commodo et incididunt sunt reprehenderit eu labore et incididunt enim ullamco aute.',
  'Pariatur proident eiusmod velit proident nisi velit sit laboris quis ea minim.',
  'Incididunt tempor aute tempor pariatur magna consectetur veniam nulla in culpa nostrud ad eiusmod aliquip.',
  'Duis officia excepteur culpa voluptate consectetur sunt nostrud cupidatat.',
  'Ea dolore labore labore id aliquip nostrud fugiat nostrud nostrud.',
  'Eu ipsum eu adipisicing velit eiusmod nulla.',
  'Fugiat sint anim laborum velit elit commodo.',
  'Do veniam commodo deserunt amet.',
  'Cupidatat reprehenderit enim officia sint duis quis eiusmod et pariatur.',
  'Consequat culpa fugiat nisi ad mollit labore eu ex laborum aliqua minim reprehenderit pariatur.',
  'Veniam Lorem sit sunt in elit dolor.',
  'Nisi commodo consectetur occaecat nisi.',
  'Eu laboris id sit anim laborum elit ea.',
  'Veniam pariatur magna commodo voluptate pariatur officia laborum.',
  'Sint cupidatat cillum mollit Lorem velit nulla amet elit in Lorem consectetur exercitation labore.',
  'Id Lorem et consectetur amet eiusmod ut commodo laboris pariatur.',
  'Amet et esse officia sunt laboris sint tempor velit sint duis consequat ut officia.',
  'Do dolore culpa ea culpa exercitation adipisicing dolore minim.',
  'Enim excepteur aliquip sit consectetur officia pariatur ad eiusmod tempor.',
  'Consectetur officia labore deserunt laborum id aliqua proident id mollit cupidatat.',
  'Dolor dolor et cupidatat aliquip deserunt laboris.',
  'Eu duis ullamco mollit anim qui ut nulla veniam do sunt et in.',
  'Sunt proident nulla nostrud cupidatat aliqua ipsum id labore ea proident ipsum laboris sit ipsum.',
  'Amet amet culpa occaecat proident quis mollit nostrud sunt anim.',
  'Consequat laboris quis sit sint nisi consectetur fugiat reprehenderit officia.',
  'Aliquip labore eu ea consequat ea minim commodo.',
  'Minim sunt cupidatat nostrud exercitation veniam occaecat duis esse Lorem et nisi.',
  'Eu nostrud exercitation dolor et pariatur in qui deserunt magna ex dolore qui elit cillum.',
  'Consectetur voluptate exercitation culpa nostrud aliquip laborum enim.',
  'Dolore adipisicing incididunt sint est dolore velit est consequat mollit.',
  'Excepteur commodo ex est laboris.',
  'Lorem deserunt cillum consequat deserunt deserunt velit cupidatat esse.',
  'Tempor nulla nulla id officia eu esse laboris veniam ex incididunt tempor elit.',
  'Exercitation incididunt cillum velit sint reprehenderit laboris.',
  'Exercitation nisi minim non ullamco do fugiat anim deserunt id consequat et.',
  'Duis cupidatat ex et nostrud sint voluptate duis voluptate et anim aliqua.',
  'Sit qui consequat exercitation aute labore consectetur voluptate aliqua est do duis.',
  'Nisi cupidatat elit quis laboris ipsum labore fugiat amet labore excepteur deserunt ut sunt.',
  'Incididunt fugiat ut anim pariatur enim duis.',
  'Proident qui sit proident dolor do adipisicing eu nisi elit excepteur.',
  'Fugiat veniam veniam officia ea consequat ut.',
  'In irure sit in qui labore duis.',
  'Dolor veniam consectetur aliquip anim magna laborum voluptate occaecat officia id culpa ipsum amet.',
  'In voluptate nisi id cillum nostrud culpa sint.',
  'Commodo ut voluptate veniam sint ut fugiat non dolore est.',
  'Labore aute id excepteur anim reprehenderit labore eu pariatur.',
  'Velit dolor veniam nulla velit quis fugiat occaecat quis magna ipsum minim elit.',
  'Officia ut dolor ea pariatur ullamco.',
  'Proident minim deserunt consequat velit.',
  'In officia cupidatat magna ea veniam fugiat officia fugiat officia esse laboris enim.',
  'Elit adipisicing ullamco dolor eiusmod laboris sunt irure reprehenderit velit minim laboris dolore irure nulla.',
  'Nulla ea sint aliqua ipsum ad laboris laboris.',
  'Laborum amet sit eiusmod tempor sunt reprehenderit occaecat.',
  'Consectetur enim ut aliquip officia officia deserunt.',
  'Nostrud commodo laboris deserunt tempor nisi proident exercitation ex in minim exercitation excepteur.',
  'Pariatur consequat quis commodo officia do exercitation ut enim laborum ullamco in ut.',
  'Nulla cupidatat Lorem commodo est sint aliquip irure culpa proident minim culpa.',
  'Amet quis nulla voluptate cillum esse voluptate veniam ad mollit.',
  'Ullamco qui id veniam ad.',
  'Ullamco irure occaecat incididunt occaecat ex quis.',
  'Eu culpa consectetur culpa fugiat consequat sint.',
  'Eiusmod dolore voluptate commodo quis ex sunt cupidatat sint.',
  'Est ex dolore enim nulla elit sint ut in exercitation laboris incididunt.',
  'Consectetur cupidatat aute anim pariatur minim tempor irure sint cupidatat.',
  'Nisi culpa deserunt voluptate quis qui.',
  'Eu dolor nostrud ullamco velit voluptate sit aliquip occaecat aute occaecat irure.',
  'Labore officia dolore nisi ad anim ipsum non ea exercitation enim amet.',
  'Non nostrud qui adipisicing elit labore magna.',
  'Non id dolore velit laborum.',
  'Cupidatat non esse minim id.',
  'Labore irure proident dolore consectetur laboris non ad sit proident adipisicing.',
  'Laborum commodo occaecat aute veniam excepteur.',
  'Qui ipsum consequat labore exercitation ea officia excepteur elit enim voluptate veniam anim enim Lorem.',
  'Dolore sit aliqua veniam veniam officia reprehenderit aliquip.',
  'Eiusmod mollit do labore laboris anim proident incididunt occaecat Lorem.',
  'Veniam non anim ex aute ipsum culpa amet aliqua Lorem.',
  'Nisi ipsum minim dolore velit.',
  'Nulla proident laboris aliquip eu et cillum excepteur minim ullamco mollit quis do.',
  'Elit sint deserunt commodo reprehenderit aliquip culpa esse veniam voluptate officia aliqua mollit sunt fugiat.',
  'Lorem culpa sint do exercitation elit esse cillum nisi.',
  'Eiusmod sunt duis et consectetur adipisicing ea nisi est.',
  'Incididunt nulla qui nulla nisi deserunt quis eu eu.',
  'Eiusmod amet aliquip magna officia dolor consequat ad labore in excepteur ut.',
  'Quis dolor aute ex veniam occaecat.',
  'Labore minim occaecat deserunt reprehenderit mollit qui.',
  'Enim veniam exercitation ullamco excepteur veniam officia ut pariatur dolor veniam sunt in laborum.',
  'Laboris quis eu ex id ea.',
  'Cupidatat occaecat aliqua ipsum ex Lorem tempor dolor dolor irure culpa veniam pariatur pariatur.',
  'Dolor excepteur reprehenderit mollit culpa officia anim deserunt fugiat reprehenderit qui aute excepteur reprehenderit sit.',
  'Amet ex tempor veniam eiusmod fugiat.',
  'Anim nostrud anim laborum mollit cupidatat nulla labore consequat aliquip.',
  'Do officia enim do quis laborum sunt fugiat velit laboris incididunt consequat voluptate.',
  'Sunt duis ad do sit adipisicing.',
  'Labore esse eu aliquip quis veniam aliquip enim mollit exercitation.',
  'Dolor sint reprehenderit enim cupidatat eiusmod nulla aliquip sunt adipisicing commodo.',
  'Minim et consequat non occaecat exercitation minim.',
  'Ex voluptate velit laboris proident culpa voluptate velit consectetur laborum adipisicing deserunt.',
  'Sunt cillum amet amet mollit enim consequat.'
]

export const generateRandomGreetings = (total = 10) => {
  return [...new Array(total)].map((_, i) => ({
    active: true,
    text: items[i > items.length - 1 ? i % items.length : i]
  }))
}
